package com.zhjl.qihao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhjl.qihao.abrefactor.db.GroupBuyingBean;
import com.zhjl.qihao.abrefactor.db.PublicBenefitActivitiesBean;
import com.zhjl.qihao.abrefactor.db.SeckillBean;
import com.zhjl.qihao.abrefactor.db.ShopListFourBean;
import com.zhjl.qihao.abrefactor.db.ShopListOneBean;
import com.zhjl.qihao.abrefactor.db.ShopListTwoBean;
import com.zhjl.qihao.freshshop.bean.SearchHistoryBean;
import com.zhjl.qihao.nearbyinteraction.bean.SearchNoteBean;

import com.zhjl.qihao.greendao.GroupBuyingBeanDao;
import com.zhjl.qihao.greendao.PublicBenefitActivitiesBeanDao;
import com.zhjl.qihao.greendao.SeckillBeanDao;
import com.zhjl.qihao.greendao.ShopListFourBeanDao;
import com.zhjl.qihao.greendao.ShopListOneBeanDao;
import com.zhjl.qihao.greendao.ShopListTwoBeanDao;
import com.zhjl.qihao.greendao.SearchHistoryBeanDao;
import com.zhjl.qihao.greendao.SearchNoteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupBuyingBeanDaoConfig;
    private final DaoConfig publicBenefitActivitiesBeanDaoConfig;
    private final DaoConfig seckillBeanDaoConfig;
    private final DaoConfig shopListFourBeanDaoConfig;
    private final DaoConfig shopListOneBeanDaoConfig;
    private final DaoConfig shopListTwoBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;
    private final DaoConfig searchNoteBeanDaoConfig;

    private final GroupBuyingBeanDao groupBuyingBeanDao;
    private final PublicBenefitActivitiesBeanDao publicBenefitActivitiesBeanDao;
    private final SeckillBeanDao seckillBeanDao;
    private final ShopListFourBeanDao shopListFourBeanDao;
    private final ShopListOneBeanDao shopListOneBeanDao;
    private final ShopListTwoBeanDao shopListTwoBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;
    private final SearchNoteBeanDao searchNoteBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupBuyingBeanDaoConfig = daoConfigMap.get(GroupBuyingBeanDao.class).clone();
        groupBuyingBeanDaoConfig.initIdentityScope(type);

        publicBenefitActivitiesBeanDaoConfig = daoConfigMap.get(PublicBenefitActivitiesBeanDao.class).clone();
        publicBenefitActivitiesBeanDaoConfig.initIdentityScope(type);

        seckillBeanDaoConfig = daoConfigMap.get(SeckillBeanDao.class).clone();
        seckillBeanDaoConfig.initIdentityScope(type);

        shopListFourBeanDaoConfig = daoConfigMap.get(ShopListFourBeanDao.class).clone();
        shopListFourBeanDaoConfig.initIdentityScope(type);

        shopListOneBeanDaoConfig = daoConfigMap.get(ShopListOneBeanDao.class).clone();
        shopListOneBeanDaoConfig.initIdentityScope(type);

        shopListTwoBeanDaoConfig = daoConfigMap.get(ShopListTwoBeanDao.class).clone();
        shopListTwoBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        searchNoteBeanDaoConfig = daoConfigMap.get(SearchNoteBeanDao.class).clone();
        searchNoteBeanDaoConfig.initIdentityScope(type);

        groupBuyingBeanDao = new GroupBuyingBeanDao(groupBuyingBeanDaoConfig, this);
        publicBenefitActivitiesBeanDao = new PublicBenefitActivitiesBeanDao(publicBenefitActivitiesBeanDaoConfig, this);
        seckillBeanDao = new SeckillBeanDao(seckillBeanDaoConfig, this);
        shopListFourBeanDao = new ShopListFourBeanDao(shopListFourBeanDaoConfig, this);
        shopListOneBeanDao = new ShopListOneBeanDao(shopListOneBeanDaoConfig, this);
        shopListTwoBeanDao = new ShopListTwoBeanDao(shopListTwoBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);
        searchNoteBeanDao = new SearchNoteBeanDao(searchNoteBeanDaoConfig, this);

        registerDao(GroupBuyingBean.class, groupBuyingBeanDao);
        registerDao(PublicBenefitActivitiesBean.class, publicBenefitActivitiesBeanDao);
        registerDao(SeckillBean.class, seckillBeanDao);
        registerDao(ShopListFourBean.class, shopListFourBeanDao);
        registerDao(ShopListOneBean.class, shopListOneBeanDao);
        registerDao(ShopListTwoBean.class, shopListTwoBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
        registerDao(SearchNoteBean.class, searchNoteBeanDao);
    }
    
    public void clear() {
        groupBuyingBeanDaoConfig.clearIdentityScope();
        publicBenefitActivitiesBeanDaoConfig.clearIdentityScope();
        seckillBeanDaoConfig.clearIdentityScope();
        shopListFourBeanDaoConfig.clearIdentityScope();
        shopListOneBeanDaoConfig.clearIdentityScope();
        shopListTwoBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
        searchNoteBeanDaoConfig.clearIdentityScope();
    }

    public GroupBuyingBeanDao getGroupBuyingBeanDao() {
        return groupBuyingBeanDao;
    }

    public PublicBenefitActivitiesBeanDao getPublicBenefitActivitiesBeanDao() {
        return publicBenefitActivitiesBeanDao;
    }

    public SeckillBeanDao getSeckillBeanDao() {
        return seckillBeanDao;
    }

    public ShopListFourBeanDao getShopListFourBeanDao() {
        return shopListFourBeanDao;
    }

    public ShopListOneBeanDao getShopListOneBeanDao() {
        return shopListOneBeanDao;
    }

    public ShopListTwoBeanDao getShopListTwoBeanDao() {
        return shopListTwoBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

    public SearchNoteBeanDao getSearchNoteBeanDao() {
        return searchNoteBeanDao;
    }

}
