package com.zhjl.qihao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhjl.qihao.abrefactor.db.PublicBenefitActivitiesBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PUBLIC_BENEFIT_ACTIVITIES_BEAN".
*/
public class PublicBenefitActivitiesBeanDao extends AbstractDao<PublicBenefitActivitiesBean, Long> {

    public static final String TABLENAME = "PUBLIC_BENEFIT_ACTIVITIES_BEAN";

    /**
     * Properties of entity PublicBenefitActivitiesBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Url_name = new Property(1, String.class, "url_name", false, "URL_NAME");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property Logo = new Property(3, String.class, "logo", false, "LOGO");
        public final static Property Note = new Property(4, String.class, "note", false, "NOTE");
        public final static Property Shopid = new Property(5, String.class, "shopid", false, "SHOPID");
        public final static Property Shopname = new Property(6, String.class, "shopname", false, "SHOPNAME");
        public final static Property Service_cell = new Property(7, String.class, "service_cell", false, "SERVICE_CELL");
    }


    public PublicBenefitActivitiesBeanDao(DaoConfig config) {
        super(config);
    }
    
    public PublicBenefitActivitiesBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PUBLIC_BENEFIT_ACTIVITIES_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"URL_NAME\" TEXT," + // 1: url_name
                "\"URL\" TEXT," + // 2: url
                "\"LOGO\" TEXT," + // 3: logo
                "\"NOTE\" TEXT," + // 4: note
                "\"SHOPID\" TEXT," + // 5: shopid
                "\"SHOPNAME\" TEXT," + // 6: shopname
                "\"SERVICE_CELL\" TEXT);"); // 7: service_cell
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PUBLIC_BENEFIT_ACTIVITIES_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PublicBenefitActivitiesBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url_name = entity.getUrl_name();
        if (url_name != null) {
            stmt.bindString(2, url_name);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(4, logo);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(5, note);
        }
 
        String shopid = entity.getShopid();
        if (shopid != null) {
            stmt.bindString(6, shopid);
        }
 
        String shopname = entity.getShopname();
        if (shopname != null) {
            stmt.bindString(7, shopname);
        }
 
        String service_cell = entity.getService_cell();
        if (service_cell != null) {
            stmt.bindString(8, service_cell);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PublicBenefitActivitiesBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url_name = entity.getUrl_name();
        if (url_name != null) {
            stmt.bindString(2, url_name);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(4, logo);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(5, note);
        }
 
        String shopid = entity.getShopid();
        if (shopid != null) {
            stmt.bindString(6, shopid);
        }
 
        String shopname = entity.getShopname();
        if (shopname != null) {
            stmt.bindString(7, shopname);
        }
 
        String service_cell = entity.getService_cell();
        if (service_cell != null) {
            stmt.bindString(8, service_cell);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PublicBenefitActivitiesBean readEntity(Cursor cursor, int offset) {
        PublicBenefitActivitiesBean entity = new PublicBenefitActivitiesBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // logo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // note
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // shopid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // shopname
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // service_cell
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PublicBenefitActivitiesBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLogo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNote(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setShopid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setShopname(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setService_cell(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PublicBenefitActivitiesBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PublicBenefitActivitiesBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PublicBenefitActivitiesBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
